### ISSUE TITLE
Menu icons aren't always Dashicons

### ISSUE THREAD

**Issue by morganestes** [highrisedigital/better-admin-post-types#8]
If an icon is registered with `$menu_icon` that's not a Dashicon, it gets printed to the `span` in https://github.com/highrisedigital/better-admin-post-types/blob/master/inc/admin/admin-menu-content.php#L67, which prevents it from displaying properly.

For example, I have a CPT registered with an SVG string which shows up in the Admin UI as expected, but gets injected into the DOM as class name instead of as an image.
If I change to a URL, it's treated as a class name instead of the `src` attribute of an `img` element, as expected.

Since CPTs can be registered with values for `$menu_icon` other than Dashicons, (see https://developer.wordpress.org/reference/functions/register_post_type/#parameters), add conditional checks to determine what's been registered before using it.

**Comment by wpmark** [comment]
Good shout - I hadn't thought of that. Thanks for Pull request and I have added a comment in there.
